version: "3"
services:
  example:
    image: ghcr.io/rustpanda/docker-template-test:main
    environment:
      - NODE_ID={{.Node.ID}}
      - NODE_HOSTNAME={{.Node.Hostname}}
    ports:
      - 8000:8080
      
